Rscript xwas_logistic_subset.R -n 'urban univariate 2007' -o 'urban_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_urban.csv' -s 'univariate_urban_07' 
Rscript xwas_logistic_subset.R -n 'rural univariate 2007' -o 'rural_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_rural.csv' -s 'univariate_rural_07' 
Rscript xwas_logistic_subset.R -n 'age1 univariate 2007' -o 'age1_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_age1.csv' -s 'univariate_age1_07'
Rscript xwas_logistic_subset.R -n 'age2 univariate 2007' -o 'age2_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_age2.csv' -s 'univariate_age2_07'
Rscript xwas_logistic_subset.R -n 'age3 univariate 2007' -o 'age3_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_age3.csv' -s 'univariate_age3_07'
Rscript xwas_logistic_subset.R -n 'tested univariate 2007' -o 'tested_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_tested.csv' -s 'univariate_tested_07'
Rscript xwas_logistic_subset.R -n 'never tested univariate 2007' -o 'never_tested_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_nevertested.csv' -s 'univariate_nevertested_07'
Rscript xwas_logistic_subset.R -n 'poor univariate 2007' -o 'poor_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_poor.csv' -s 'univariate_poor_07'
Rscript xwas_logistic_subset.R -n 'rich univariate 2007' -o 'rich_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_rich.csv' -s 'univariate_rich_07'
Rscript xwas_logistic_subset.R -n 'wealth1 univariate 2007' -o 'wealth1_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_wealth1.csv' -s 'univariate_wealth1_07'
Rscript xwas_logistic_subset.R -n 'wealth2 univariate 2007' -o 'wealth2_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_wealth2.csv' -s 'univariate_wealth2_07'
Rscript xwas_logistic_subset.R -n 'wealth3 univariate 2007' -o 'wealth3_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_wealth3.csv' -s 'univariate_wealth3_07'
Rscript xwas_logistic_subset.R -n 'wealth4 univariate 2007' -o 'wealth4_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_wealth4.csv' -s 'univariate_wealth4_07'
Rscript xwas_logistic_subset.R -n 'wealth5 univariate 2007' -o 'wealth5_univariate_07.Rdata' -f '../data/hiv xwas Zambia07 dataset v7_wealth5.csv' -s 'univariate_wealth5_07'